on:
  push:
    branches:
    - master

name: Update github star

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.7
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install starred
      - name: Set github config
        run: |
          git config --global user.email "amor90s.zhang@gmail.com"
          git config --global user.name "amorist"
      - name: Starred
        run: |
          export GITHUB_TOKEN=${{ secrets.PERSONAL_TOKEN }}
          python starred.py
